--2.2.4
create view ACTOR_80(ACTID,ANAME,BYEAR,NUMBER,MAXGRADE)
as
select ACTOR.ACTID,ANAME,BYEAR,count(*),max(GRADE)
from ACTOR,ACTIN
where ACTOR.BYEAR>=1980 and ACTOR.BYEAR<=1989 and ACTIN.ISLEADING='Y'
group by ACTOR.ACTID,ACTIN.ACTID;